properties:
  cookie: ${PARSER_COOKIE}
  delaySeconds: ${PARSER_DELAY}

server:
  port: ${PARSER_PORT:8181}

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    com.parser.parser.svc.banner: DEBUG

spring:
  datasource:
    url: ${PARSER_DATASOURCE}
    username: ${PARSER_DB_USER}
    password: ${PARSER_DB_PASSWORD}
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/ddl/changelog-master.xml
    default-schema: public
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true