# тут можно переопределить настройки, чтобы запускать spring application из IDE без докера
# ну например настройки базы прописать, чтобы не задвать переменные окружения
spring:
  datasource:
    url: 'jdbc:postgresql://service-db/parser_db'
    username: nihauma
    password: mnepoxyi
properties:
  cookie: 5
  delaySeconds: ${PARSER_DELAY}