properties:
  cookie: ${PARSER_COOKIE}
  delaySeconds: ${PARSER_DELAY}

server:
  port: ${PARSER_PORT:8181}

spring:
  datasource:
    url: ${PARSER_DATASOURCE}
    username: ${PARSER_DB_USER}
    password: ${PARSER_DB_PASSWORD}
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: public
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true